on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      
jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        run: |
          helm version
          helm template demochart
